import Footer from "./components/footer";
import Header from "./components/header";
import { Provider } from "./components/ui/provider";

export const metadata = {
	title: "Hazelwood Outdoors",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Provider>
					<Header />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
