import './globals.css'
import Footer from "./components/footer";
import Header from "./components/header";
import { Provider } from "./components/ui/provider";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
	subsets: ["latin"],
	weight: ['100','200','300','400','500','600','700','800','900'],
	display: 'auto',
	style: ["normal", "italic"]
})

export const metadata = {
	title: "Hazelwood Outdoors",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Provider>
					<Header />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
